language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="ppx_graphql:."
  - DISTRO=debian-stable
  matrix:
  - PACKAGE="ppx_graphql" OCAML_VERSION="4.04.1"
  - PACKAGE="ppx_graphql" OCAML_VERSION="4.05.0"
  - PACKAGE="ppx_graphql" OCAML_VERSION="4.06.1"
  - PACKAGE="ppx_graphql" OCAML_VERSION="4.07.1"
  - PACKAGE="ppx_graphql" OCAML_VERSION="4.08.1"
  - PACKAGE="ppx_graphql" OCAML_VERSION="4.09.0"
